### PR TITLE
Training Updates

### PR DESCRIPTION
**Pull request by ansoncfit**
Various fixes/updates for upcoming training

### CODE REVIEW

**Comment by bstabler** [comment]
@ansoncfit - do you think I should review? or maybe Max?

**Comment by ansoncfit** [comment]
@jslason a review of this for clarity would be appreciated. Note we have revised the suggested source for OSM extracts (see https://docs.conveyal.com/prepare-inputs#downloading)

Before merging, I plan to revert https://github.com/RSGInc/ladot_analysis_dataprep/pull/9/commits/122ea317ed06f94575d88c9b9f44cedc28ca7558 to switch back to higher accuracy elevation sampling.

**Comment by bstabler** [comment]
@jslason - please review, thanks!

**Comment by jslason** [comment]
@ansoncfit  should I delete the training-updates branch?

**Comment by ansoncfit** [comment]
@jslason Thanks for the review/merge. Let's actually keep the branch around, because I think some links sent around previously may refer to it.

**Pull request merged**
